/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleTest01;
        
public class App
{
    public String getGreeting()
    {
        return "Hello World! Yo !";
    }
    
    public static int listtest2()
    {
        LinkedList lst1 = new LinkedList();
        lst1.addTail(18);
        lst1.addTail(35);
        lst1.addTail(69);
        lst1.addHead(0);
        lst1.printnum();
        lst1.prtnumback();
        System.out.println("Head: " + lst1.head.num);
        System.out.println("Tail: " + lst1.tail.num);
        System.out.println("Length: " + lst1.len);
        
        lst1.delTail();
        lst1.printnum();
        lst1.prtnumback();
        System.out.println("\nHead: " + lst1.head.num);
        System.out.println("Tail: " + lst1.tail.num);
        System.out.println("Length: " + lst1.len);
        return 0;
    }
    
    public static void main(String[] args) {
        listtest2();
        System.out.println("\n" + (new App().getGreeting()));
    }
}
