/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleTest01;
        
public class App
{
    public String getGreeting()
    {
        return "Hello World! Yo !";
    }
    
    public static int listtest()
    {
        LinkedList lst1 = new LinkedList(7);
        LinkedList.Node secnd = new LinkedList.Node(13);
        LinkedList.Node third = new LinkedList.Node(25);
        lst1.head.next = secnd;
        secnd.next = third;
        lst1.print();
        return 0;
    }

    public static void main(String[] args) {
        listtest();
        System.out.println("\n" + (new App().getGreeting()));
    }
}
